# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale: en-GB
title: Ilias Bartolini
title_separator: '-'
description: >- # this means to ignore newlines until "baseurl:"
  Personal stories, technology and social justice.
baseurl: "" # the subpath of your site, e.g. /blog
name: Ilias Bartolini
email: ilias.bartolini@gmail.com
copyright: '<style>.remove-external-link-icon:after { content: none !important; }</style>This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.<br/><a class="remove-external-link-icon"  rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img style="display: inline; margin: 0.2rem; border-width:0" alt="Creative Commons Licence" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a>'

url: "http://iliasbartolini.name" # the base hostname & protocol for your site, e.g. http://example.com
repository: "iliasbartolini/iliasbartolini.name"

author:
  name: Ilias Bartolini
  email: ilias.bartolini@gmail.com
  picture: /assets/images/ilias-bartolini-avatar.jpg
  social:
    rss: http://iliasbartolini.name/feed.xml
    twitter: iliasbartolini
    facebook: iliasbartolini
    lastfm: brain79
    flickr: iliasbartolini
    linkedin: iliasbartolini
    github: iliasbartolini
    stackoverflow: 225358/ilias-bartolini
    email: mailto:ilias.bartolini@gmail.com

# Build settings
markdown: kramdown
theme: jekyll-theme-hydejack
accent_image: /assets/images/lencois-bg.jpg

layout: list
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-avatar
  - jemoji

disqus: iliasbartolini-name
google_analytics: UA-28181963-2

pagination:
  enabled: true
  per_page: 5
  title: ':title - page :num'
  permalink: '/page/:num/'
  sort_reverse: true

defaults:
  - scope:
      path: _pages/about.md
    values:
      menu: true
      order: 1
  - scope:
      path: _pages/contact.md
    values:
      menu: true
      order: 2
  - scope:
      path: _pages/updates.md
    values:
      menu: true
      order: 2

collections:
  featured_tags:
    permalink:         /tag/:name/
    output:            true

excerpt_separator: <!--more-->


# defaults:
#   # _posts
#   - scope:
#       path: ""
#       type: posts
#     values:
#       layout: single
#       comments: true
#       read_time: true
#       author_profile: false
#       author: Ilias Bartolini
#       share: true
#       related: true
#   # _pages
#   - scope:
#       path: ""
#       type: pages
#     values:
#       layout: single
#       comments: false
#       read_time: false
#       author_profile: false
#       author: Ilias Bartolini

# category_archive:
#   type: jekyll-archives
#   path: /categories/
# tag_archive:
#   type: jekyll-archives
#   path: /tags/
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


pagination:
  enabled: true
  per_page: 5
  title: ':title - page :num'
  permalink: '/page/:num/'
  sort_reverse: true

compress_html:
  comments:            ['<!-- ', ' -->']
  clippings:           all
  endings:             all

sass:
  style:               compressed

hydejack:

include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _site/
  - .idea/
  - README.md
  - .git/

compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environment
