# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale: en-GB
title: Ilias Bartolini's home #TODO: better title
title_separator: '-'
description: >- # this means to ignore newlines until "baseurl:"
  This is Ilias Bartolini's blog
  Personal stories and information on technology and social justice
baseurl: "" # the subpath of your site, e.g. /blog
name: Ilias Bartolini
email: ilias.bartolini@gmail.com
##copyright: 'Licensed under <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.<br/><a class="remove-external-link-icon"  rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img style="display: inline; margin: 0.2rem; border-width:0" alt="Creative Commons Licence" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a>'

url: "http://iliasbartolini.name" # the base hostname & protocol for your site, e.g. http://example.com
repository: "iliasbartolini/iliasbartolini.name"

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: dark

comments:
  provider: "disqus"
  disqus:
    shortname: "iliasbartolini-name"

search: true

author:
  name: "Ilias Bartolini"
  bio: "Soit gentil at tiens courage"
  avatar: "/assets/images/ilias-bartolini-avatar.jpg"
  twitter: "iliasbartolini"
  facebook: "iliasbartolini"
  lastfm: brain79
  flickr: iliasbartolini
  linkedin: iliasbartolini
  github: iliasbartolini
  keybase: "iliasbartolini"

twitter:
  username: "iliasbartolini"

####Open Graph image
#og_image: /assets/images/site-logo.png

#teaser: /assets/images/header.jpg

social:
  name: Ilias Bartolini
  links:
    - "https://twitter.com/iliasbartolini"
    - "https://facebook.com/iliasbartolini"
    - "https://www.linkedin.com/in/iliasbartolini"

analytics:
  provider: "google-universal"
  google:
    tracking_id: "UA-28181963-2"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      comments: true
      read_time: true
      author_profile: false
      author: Ilias Bartolini
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      comments: false
      read_time: false
      author_profile: false
      author: Ilias Bartolini

category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/


paginate: 5
paginate_path: /page/:num/


include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _site/
  - .idea/
  - README.md

compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environment
